name: material_dialog
description: A new Flutter package.
version: 0.0.1
author: Go_oG

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.1.6
  liquid_swipe: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  swipe_stack: ^1.0.0  

flutter:
  uses-material-design: true
